### ISSUE TITLE
event handle err

### ISSUE THREAD

**Issue by Rainerino** [Rainerino/CPEN-321#11]
```bash
web_1  | > Study-Buddy@1.0.0 start /starter
web_1  | > node app.js
web_1  | 
web_1  | Connected: MongoDB is connected at mongodb+srv://user:454943484@cluster0-nfpde.mongodb.net
/populate?retryWrites=true&w=majority.
web_1  | Running: Socket.io app is running on port 3000
web_1  | Running: App is running at http://localhost:8080 in development mode
web_1  |   Press CTRL-C to stop
web_1  | 
web_1  | Time:  1574082144028
web_1  | POST /user/login 200 99.532 ms - 808
web_1  | Time:  1574082146981
web_1  | Time:  1574082146985
web_1  | events.js:183
web_1  |       throw er; // Unhandled 'error' event
web_1  |       ^
web_1  | 
web_1  | TypeError: Cannot read property 'suggestedFriendList' of null
web_1  |     at User.findById (/starter/controllers/user.js:302:39)
web_1  |     at /starter/node_modules/mongoose/lib/model.js:4604:16
web_1  |     at /starter/node_modules/mongoose/lib/query.js:4351:12
web_1  |     at model.Query.Query._completeOne (/starter/node_modules/mongoose/lib/query.js:2054:12
)
web_1  |     at Immediate.Query.base.findOne.call (/starter/node_modules/mongoose/lib/query.js:2116
:10)
web_1  |     at Immediate._onImmediate (/starter/node_modules/mquery/lib/utils.js:116:16)
web_1  |     at runCallback (timers.js:810:20)
web_1  |     at tryOnImmediate (timers.js:768:5)
web_1  |     at processImmediate [as _immediateCallback] (timers.js:745:5)
web_1  | npm ERR! code ELIFECYCLE
web_1  | npm ERR! errno 1
web_1  | npm ERR! Study-Buddy@1.0.0 start: `node app.js`
web_1  | npm ERR! Exit status 1
web_1  | npm ERR! 
web_1  | npm ERR! Failed at the Study-Buddy@1.0.0 start script.
web_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging outpu
t above.
web_1  | 
web_1  | npm ERR! A complete log of this run can be found in:
web_1  | npm ERR!     /root/.npm/_logs/2019-11-18T13_02_27_077Z-debug.log
```

**Comment by Rainerino** [comment]
solved by ensure that suggested friendlist are filled upon login
