### ISSUE TITLE
refresh database cause the userId stored becomes invalid 

### ISSUE THREAD

**Issue by Rainerino** [Rainerino/CPEN-321#12]
nodejs
```bash
web_1  | Time:  1574091588463
web_1  | GET /user/5dd284b4993f92035815be24/suggested-friends 400 75.260 ms - 11
web_1  | GET /user/5dd284b4993f92035815be24/friendlist - - ms - -
web_1  | TypeError: Cannot read property 'location' of null
web_1  |     at userList.filter (/starter/core/suggestion.js:27:28)
web_1  |     at Array.filter (<anonymous>)
web_1  |     at Object.exports.suggestNearbyUser (/starter/core/suggestion.js:21:27)
web_1  |     at <anonymous>
web_1  |     at process._tickCallback (internal/process/next_tick.js:189:7)
```
AS
```bash
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.study_buddy, PID: 13668
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at com.example.study_buddy.fragments.FriendsFragment$2.onResponse(FriendsFragment.java:118)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/EGL_emulation: eglMakeCurrent: 0xebbd54e0: ver 2 0 (tinfo 0xebc34b40)
I/Process: Sending signal. PID: 13668 SIG: 9
Process 13668 terminated.
```

**Comment by Rainerino** [comment]
In the frontend, now it will load the user again even if the userId is saved, and check if the user exist or not by reading the status code
