### ISSUE TITLE
null user location 

### ISSUE THREAD

**Issue by Rainerino** [Rainerino/CPEN-321#13]
```bash
(node:22240) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at l (/home/yiyi/Documents/CPEN-321/node_modules/geolib/lib/index.js:1:1859)
    at t (/home/yiyi/Documents/CPEN-321/node_modules/geolib/lib/index.js:1:3252)
    at S (/home/yiyi/Documents/CPEN-321/node_modules/geolib/lib/index.js:1:3948)
    at Module.D (/home/yiyi/Documents/CPEN-321/node_modules/geolib/lib/index.js:1:5951)
    at /home/yiyi/Documents/CPEN-321/core/suggestion.js:26:29
    at Array.filter (<anonymous>)
    at Object.exports.suggestNearbyUser (/home/yiyi/Documents/CPEN-321/core/suggestion.js:21:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/yiyi/Documents/CPEN-321/controllers/user.js:48:46
(node:22240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
POST /user/login - - ms - -

```

**Comment by Rainerino** [comment]
LOL still not handled

**Comment by Rainerino** [comment]
The frontend will send a dummy location if it's not found
